plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lightjalao.game'
    compileSdk 35

    defaultConfig {
        applicationId "com.lightjalao.game"
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName "1.1.2"
    }

    signingConfigs {
        debug {
            storeFile file('../debug.keystore')
            storePassword 'lightjalao-test'
            keyAlias 'lightjalao'
            keyPassword 'lightjalao-test'
        }
    }

    buildTypes {
        debug {
            debuggable true
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt']
        }
    }
}


dependencies {
    implementation 'com.google.android.gms:play-services-ads:25.5.0'
}
